In [1]:
from sklearn.externals import joblib

In [3]:
x = joblib.load("/mnt/share/vbs-power-line-fault-detection/features/summary/window_40_step_20/train/feature.pickle")

In [7]:
x2 = joblib.load("/mnt/share/vbs-power-line-fault-detection/features/summary/aug/window_40_step_20/train/0/raw.pickle")

In [10]:
x2.shape

(39999, 15)

In [8]:
x2[:10]

array([[ 0.14235294,  0.00470588, -0.14666667,  0.00448844,  0.0045733 ,
         0.00531947,  0.15294118,  0.01176471, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.16078431,  0.14509804,  0.00392157, -0.14509804],
       [ 0.14235294,  0.00470588, -0.14686275,  0.00512812,  0.00520255,
         0.00540195,  0.15294118,  0.01960784, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.16078431,  0.14509804,  0.00392157, -0.14509804],
       [ 0.14392157,  0.00529412, -0.14686275,  0.00569641,  0.00551465,
         0.00479892,  0.15294118,  0.01960784, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.15294118,  0.14509804,  0.00392157, -0.14509804],
       [ 0.14294118,  0.00411765, -0.14843137,  0.00581332,  0.00510934,
         0.00460263,  0.15294118,  0.01176471, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.15294118,  0.14509804,  0.00392157, -0.14509804],
       [ 0.14352941,  0.00490196, -0.14784314,  0.00612569,  0.00586599,
         0.00512812,  0.15294118,  0.01176471, 

In [11]:
x[0].shape

(39999, 15)

In [14]:
x[0][:1]

array([[ 0.14235294,  0.00448844,  0.15294118,  0.1372549 ,  0.14509804,
         0.00470588,  0.0045733 ,  0.01176471, -0.00392157,  0.00392157,
        -0.14666667,  0.00531947, -0.1372549 , -0.16078431, -0.14509804]])

In [15]:
x2[:1]

array([[ 0.14235294,  0.00470588, -0.14666667,  0.00448844,  0.0045733 ,
         0.00531947,  0.15294118,  0.01176471, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.16078431,  0.14509804,  0.00392157, -0.14509804]])

In [27]:
import itertools

In [32]:
switched = x[0][:1][:, list(itertools.chain.from_iterable([[i, i + 5, i + 10] for i in range(5)]))]

In [33]:
switched

array([[ 0.14235294,  0.00470588, -0.14666667,  0.00448844,  0.0045733 ,
         0.00531947,  0.15294118,  0.01176471, -0.1372549 ,  0.1372549 ,
        -0.00392157, -0.16078431,  0.14509804,  0.00392157, -0.14509804]])

In [20]:
import numpy as np

In [34]:
np.testing.assert_array_almost_equal(x2[:1], switched)

In [38]:
 x[:10, :, list(itertools.chain.from_iterable([[i, i + 5, i + 10] for i in range(5)]))]

array([[[ 0.14235294,  0.00470588, -0.14666667, ...,  0.14509804,
          0.00392157, -0.14509804],
        [ 0.14235294,  0.00470588, -0.14686275, ...,  0.14509804,
          0.00392157, -0.14509804],
        [ 0.14392157,  0.00529412, -0.14686275, ...,  0.14509804,
          0.00392157, -0.14509804],
        ...,
        [ 0.1454902 ,  0.00882353, -0.14411765, ...,  0.14509804,
          0.01176471, -0.14509804],
        [ 0.14509804,  0.00784314, -0.14470588, ...,  0.14509804,
          0.00392157, -0.14509804],
        [ 0.14352941,  0.00666667, -0.14568627, ...,  0.14509804,
          0.00392157, -0.14509804]],

       [[-0.12431373, -0.03686275,  0.15686275, ..., -0.12156863,
         -0.03529412,  0.16078431],
        [-0.1245098 , -0.03705882,  0.15705882, ..., -0.12156863,
         -0.03529412,  0.16078431],
        [-0.1254902 , -0.03843137,  0.15647059, ..., -0.12156863,
         -0.03529412,  0.15294118],
        ...,
        [-0.11823529, -0.0345098 ,  0.16156863, ..., -